name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy certificates
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp Certificates/cert.p12 .
          cp Certificates/u.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install certificate
        run: |
          security create-keychain -p "" ios.keychain
          security import cert.p12 -k ios.keychain -P 'newpassword' -T /usr/bin/codesign
          security list-keychains -s ios.keychain

      - name: Install dependencies
        run: |
          sudo gem install cocoapods || true
          pod install || true

      - name: Build IPA
        run: |
          xcodebuild -workspace *.xcworkspace \
                     -scheme "INDY" \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/app.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/*.ipa
