name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest   # важный момент — сборка iOS только на macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode certificate & provisioning profile
        run: |
          echo "$P12_BASE64" | base64 --decode > cert.p12
          echo "$PROVISION_BASE64" | base64 --decode > profile.mobileprovision

      - name: Install certificate
        run: |
          security create-keychain -p "" ios.keychain
          security import cert.p12 -k ios.keychain -P '@theappbox' -T /usr/bin/codesign
          security list-keychains -s ios.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install dependencies
        run: |
          sudo gem install cocoapods || true
          pod install || true

      - name: Build IPA
        run: |
          xcodebuild -workspace *.xcworkspace \
                     -scheme "INDY" \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/app.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/*.ipa
